import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import Banner from "@/components/banner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				{/* Top most banner stays on top of all pages */}
				<Banner />
				<div style={{ height: "56px", width: "100%" }} />
				{children}
			</body>
		</html>
	);
}
